#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-eo-lm-consumer.name" . }}-pdb
  labels: {{- include "eric-eo-lm-consumer.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-eo-lm-consumer.annotations" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "eric-eo-lm-consumer.name" . }}
      release: {{ .Release.Name }}