#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.global -}}
  {{- if and .Values.global.networkPolicy -}}
    {{- if and .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-eo-lm-consumer.name" . }}-access
  labels: {{- include "eric-eo-lm-consumer.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-eo-lm-consumer.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "eric-eo-lm-consumer.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ template "eric-eo-lm-consumer.name" . }}-access: "true"
    - podSelector:
        matchLabels:
          app: eric-pm-server
    {{- end }}
  {{- end -}}
{{- end -}}
