#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq (include "eric-eo-lm-consumer.service-mesh-enabled" .) "true" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "eric-eo-lm-consumer.name" . }}-virtualservice
  labels: {{- include "eric-eo-lm-consumer.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-eo-lm-consumer.annotations" . | nindent 4 }}
spec:
  hosts:
    - {{ template "eric-eo-lm-consumer.name" . }}
  http:
    - match:
        - method:
            exact: GET
          uri:
            prefix: /
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.get.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.get.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.get.timeout }}
      route:
        - destination:
            host: {{ template "eric-eo-lm-consumer.name" . }}
            subset: {{ template "eric-eo-lm-consumer.name" . }}-v1
    - route:
        - destination:
            host: {{ template "eric-eo-lm-consumer.name" . }}
            subset: {{ template "eric-eo-lm-consumer.name" . }}-v1
{{- end }}